import assert from 'node:assert/strict';
import {createPerformanceRecorder} from '../public/performance_report.js';
import {renderBattleReport,reportCsv} from '../public/battle_report.js';
const r=createPerformanceRecorder();
r.start('a','me');r.frame(0,true,0);r.frame(16,true,0);r.frame(80,true,1);
r.load(80,1,{renderedUnits:40,drawCalls:100,geometries:60,textures:10},.8);
r.load(90,1,{renderedUnits:999},.6);
let s=r.snapshot('a','me');assert.equal(s.frames,2);assert.equal(s.over50,1);assert.equal(s.maxUnits,40);assert.equal(s.minScale,.8);
assert.equal(s.p95Ms,64);assert.equal(s.averageFps,25);
r.pause();r.frame(10000,true,10);assert.equal(r.snapshot('a','me').frames,2,'background gap excluded');
r.frame(10120,true,10);r.frame(20000,false,11);r.frame(30000,true,12);
assert.equal(r.snapshot('a','me').frames,3);assert.equal(r.snapshot('a','me').over100,1);
for(let i=1;i<=5000;i++)r.frame(30000+i*16,true,12+i*60);
s=r.snapshot('a','me');assert.ok(s.periods.length<=120);assert.equal(s.periods.reduce((n,p)=>n+p.frames,0),s.frames);
assert.equal(s.periods.reduce((n,p)=>n+p.ms,0),s.ms);
assert.equal(r.snapshot('b','me'),null);assert.equal(r.snapshot('a','other'),null);
const report={matchId:'a',duration:100,players:[{id:'me',name:'Me'}],samples:[],events:[],clientPerformance:s};
assert.ok(renderBattleReport(report,'me').includes('本机性能摘要'));
assert.ok(reportCsv(report).includes('本机性能时间段'));
assert.ok(!renderBattleReport({...report,matchId:'wrong'},'me').includes('本机性能摘要'));
s.periods[0].frames=-1;assert.notEqual(r.snapshot('a','me').periods[0].frames,-1);
r.start('b','me');assert.equal(r.snapshot('b','me'),null);
console.log('Performance report: bounded histograms/periods, hidden-tab reset, match/viewer isolation, load throttling, snapshots and safe report export passed.');
